# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gk_attendance', '0002_auto_20170713_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='students',
        ),
    ]
